# Generated by Django 4.1.5 on 2023-01-18 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата последнего обновления'
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'К выполнению'),
                            (2, 'В работе'),
                            (3, 'Выполнено'),
                            (4, 'Архив'),
                        ],
                        default=1,
                        verbose_name='Статус',
                    ),
                ),
                (
                    'priority',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'Низкий'),
                            (2, 'Средний'),
                            (3, 'Высокий'),
                            (4, 'Критический'),
                        ],
                        default=2,
                        verbose_name='Приоритет',
                    ),
                ),
                ('due_date', models.DateTimeField(verbose_name='Срок выполнения')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='GoalComment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата последнего обновления'
                    ),
                ),
                ('text', models.TextField(verbose_name='Комментарий')),
                (
                    'goal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='goals.goal',
                        verbose_name='Цель',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Автор',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='GoalCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата последнего обновления'
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                (
                    'is_deleted',
                    models.BooleanField(default=False, verbose_name='Удалена'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='goals.goalcategory',
                verbose_name='Категория',
            ),
        ),
    ]
